apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: cart
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: cart
    environment: dev
spec:
  replicas: 1
  selector:
    # Lables for replicaset to match the pods
    matchLabels:
      project: roboshop
      tier: backend
      component: cart
  # This is pod definition, pod is subset of replicaset, these are assigned to newly creating pods
  template:
    metadata:
      labels:
        project: roboshop
        tier: backend
        component: cart
    spec:
      containers:
        - name: cart
          image: adepusaikumar/cart:1.0.0
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: cart
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 2
            failureThreshold: 15
          readinessProbe:
            tcpSocket:
              port: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "150m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: cart
    environment: dev
spec:
  selector:
    project: roboshop
    tier: backend
    component: cart
  ports:
    - port: 8080  # Serivce port
      targetPort: 8080  # Container port
      protocol: TCP
    